FROM php:8.3-cli-alpine

RUN apk add --no-cache \
    postgresql-dev \
    mariadb-connector-c-dev \
    sqlite-dev

RUN docker-php-ext-install \
    pdo_pgsql \
    pdo_mysql \
    pdo_sqlite

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock ./

RUN composer install \
    --no-interaction \
    --prefer-dist

COPY src ./src
COPY config ./config
COPY tests ./tests
COPY database ./database
COPY phpunit.xml ./

CMD ["./vendor/bin/phpunit"]